### ISSUE TITLE
Create clipboard for copy/paste widgets between dashboards

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-visualization#312]
The basic concept is to put the clipboard widget data in localstorage. When it's present, a draggable item will appear in the palette and can be dragged onto another dashboard.

The problem is that `extraTables`, which defines which tables are needed in addition to the default ones in the schema, is entirely outside of the visualization library. Normally it is only changed by the table selection control, which is overridden in mWater's case to provide an interface for searching for and adding extra tables, which are then available.

However, when pasting between two dashboards, the destination may not have the extra tables needed by the widget being pasted. This poses a few problems:

* it's tricky to figure out which tables are even needed by the widget. Looking for all tables that are in the schema as strings in the JSON of the widget design would likely work, but it's a hack

* the visualization library has no concept of extra tables, so the pasting logic somehow needs to reach out of the library (via context?). Or, we need to add the concept to the visualization library, but it pollutes what has so far been a clean separation of concerns.

* adding the extra tables needed takes a few seconds (to fetch a new schema), so the pasted widget needs to be in an intermediate state during that time

@Autio We could easily implement copy/paste that works between dashboards with the same data sources right now. The problem is that pasting from one dashboard that references an indicator or form into one that doesn't will fail. It's not clear to me yet how to handle the extra tables problem yet cleanly.

**Comment by Autio** [comment]
As a first measure could we just tell the user that pasting failed because the data sources are not present? Then leave it to the user to resolve.
