### ISSUE TITLE
Add week of year axis transform

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-visualization#419]
Allow clicking on Week as an option in charts when date is the x-axis.

@Autio There are two definitions (at least) of week of year:

1) https://en.wikipedia.org/wiki/ISO_week_date#First_week (Means that Jan 1 might be in last year, but weeks go from Monday-Sunday)

2) Generic floor(day of year/7) meaning that the first week always starts on Jan 1, but doesn't go from Monday-Sunday

Which should we implement?

**Comment by Autio** [comment]
The steer from Strathclyde is to avoid weeks going from Sunday to Monday so we should go for option 1.
