### ISSUE TITLE
Support hextile maps

### ISSUE THREAD

**Issue by grassick** [mWater/mwater-visualization#420]
Allow creating a hextile with a specified size and optionally bounded by an admin region.

**Comment by grassick** [comment]
```
select count(*), loc from 
CDB_HexagonGrid(
  ST_SetSRID(
    ST_Envelope(
      ST_Collect(
        ST_MakePoint(10000000,-10000000),
        ST_MakePoint(-10000000,10000000)
      )
     ),
     3857),
   1000000) as loc
   inner join entities.community as com
   on st_contains(loc, com.location)
  group by 2
```
Or
```
select count(*), loc from 
CDB_HexagonGrid((select shape_simplified from admin_regions where full_name = 'Tanzania'), 100000) as loc
inner join entities.water_point as wp
   on st_contains(loc, wp.location)
  group by 2
```

**Comment by grassick** [comment]
Community with 1000km global grid:
```
select alias_grid as "the_geom_webmercator", width_bucket(count(*), 0, 100, 5) as "color" from (CDB_HexagonGrid(ST_MakeEnvelope(-20000000, -20000000, 20000000, 20000000, 3857), 1000000) as "alias_grid" left join (select * from entities.community) as "alias_data" on ST_Contains(alias_grid, ST_Transform(alias_data."location", 3857))) group by 1
```
1000km grid - (634 x 150000 points) - 24 seconds

2000km grid - (150 cells x 150000 points) - 5.8 seconds

Scales linearly. Too slow.

**Comment by grassick** [comment]
Scripts are all here: https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_Hexagon.sql

Would be better to convert from point location to hex grid number and then do right join to hexagon grid. Involves some pg-sql writing and some math. @Autio This one will be more complex than hoped, so I'd give it 3-4 days instead of the 2 I was hoping.

**Comment by Autio** [comment]
Ok, that's fine and it's good to be aware. We have room to up the estimate with Strathclyde.

**Comment by grassick** [comment]
https://www.redblobgames.com/grids/hexagons/#rounding has complete details on the math conversion needed to convert coordinates to hex tiles.

**Comment by grassick** [comment]
To get point: 

https://www.redblobgames.com/grids/hexagons/#rounding

function flat_hex_to_pixel(hex):
    var x = size * (     3./2 * hex.q                    )
    var y = size * (sqrt(3)/2 * hex.q  +  sqrt(3) * hex.r)
    return Point(x, y)

function pixel_to_flat_hex(point):
    var q = ( 2./3 * point.x                        ) / size
    var r = (-1./3 * point.x  +  sqrt(3)/3 * point.y) / size
    return hex_round(Hex(q, r))

function hex_round(hex):
    return cube_to_axial(cube_round(axial_to_cube(hex)))
  
function cube_round(cube):
    var rx = round(cube.x)
    var ry = round(cube.y)
    var rz = round(cube.z)

    var x_diff = abs(rx - cube.x)
    var y_diff = abs(ry - cube.y)
    var z_diff = abs(rz - cube.z)

    if x_diff > y_diff and x_diff > z_diff:
        rx = -ry-rz
    else if y_diff > z_diff:
        ry = -rx-rz
    else:
        rz = -rx-ry

    return Cube(rx, ry, rz)

function cube_to_axial(cube):
    var q = cube.x
    var r = cube.z
    return Hex(q, r)

function axial_to_cube(hex):
    var x = hex.q
    var z = hex.r
    var y = -x-z
    return Cube(x, y, z)

function cube_to_oddq(cube):
    var col = cube.x
    var row = cube.z + (cube.x - (cube.x&1)) / 2
    return OffsetCoord(col, row)

function oddq_to_cube(hex):
    var x = hex.col
    var z = hex.row - (hex.col - (hex.col&1)) / 2
    var y = -x-z
    return Cube(x, y, z)

function doubleheight_to_cube(hex):
    var x = hex.col
    var z = (hex.row - hex.col) / 2
    var y = -x-z
    return Cube(x, y, z)

function cube_to_doubleheight(cube):
    var col = cube.x
    var row = 2 * cube.z + cube.x
    return DoubledCoord(col, row)    

function doubleheight_to_pixel(hex):
    var x = size * 3/2 * hex.col
    var y = size * sqrt(3)/2 * hex.row
    return Point(x, y)

**Comment by grassick** [comment]
Using oddq format. 

hex to pixel: size * 3/2 * col as x, size * sqrt(3) * (row + 0.5 * (mod(col,2))) as y

pixel to hex:
```
q = (2.0/3 * x)/size
r = (-1.0/3 * x + sqrt(3)/3 * y)/size

rx = round(cube.x)
ry = round(cube.y)
rz = round(cube.z)

x_diff = abs(rx - cx)
y_diff = abs(ry - cy)
z_diff = abs(rz - cz)

if x_diff > y_diff and x_diff > z_diff:
    rx = -ry-rz
else if y_diff > z_diff:
    ry = -rx-rz
else:
    rz = -rx-ry

col = rx
row = rz + (rx - mod(rx, 2)) / 2
```
