### ISSUE TITLE
Error in line chart rendering

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#437]
John exported a line chart to PNG and it rendered poorly:

![unnamed](https://user-images.githubusercontent.com/5147940/70623216-49294d80-1c26-11ea-8d12-34f9524ff1c9.png)

https://portal.mwater.co/#/dashboards/5319ba279d2d468d8006e6af1e27c0cb

**Comment by broncha** [comment]
fixed in c0d46fca6211659cd44cb69fc3958118d4d2a204
