### ISSUE TITLE
Tweak stacked bar chart value display 

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#453]
WaterAid suggests we change the value for stacked bar charts to be inside the segment centre, otherwise it can be very confusing for users. 

In the below, 21.2 is for the light yellow block etc. 

![image_2021_06_28T09_16_45_418Z](https://user-images.githubusercontent.com/5147940/123616221-bef80880-d80e-11eb-9194-7204f1d8da18.png)

**Comment by broncha** [comment]
If you look closely, the Basic block does not have enough height to accommodate the value. The value for the yellow block is placed right. Its that the block for the Basic is not high enough

**Comment by Autio** [comment]
Ok, but this is still very bad for a user to read. The darker yellow reads very poorly on the light yellow, the light yellow in the red does confuse users. Is it not then better to default to have black text in the middle of a block but also have a minimum height and if that height isn't met, then the value for that block isn't rendered?

**Comment by broncha** [comment]
setting a minimum height would create confusion. We would not be setting the height and rather would need to remove small values from the dataset.
Defaulting the values text to black could work. But will not solve the small values issue

**Comment by Autio** [comment]
Ok, let's start with the black text. I suppose we can leave more advanced alternatives, like shunting an overlapping value to the side, until later if they are not trivial to implement.

![image](https://user-images.githubusercontent.com/5147940/123619337-bf45d300-d811-11eb-9a36-a2779110988f.png)

**Comment by Autio** [comment]
Cliff from Kenya also suggested a toggle option to show the label value in the start, centre, end, and call-out. Is this a feasible toggle?

**Comment by broncha** [comment]
![Screen Shot 2021-07-16 at 15 11 35](https://user-images.githubusercontent.com/46905/125925753-b82027fb-ec81-4ab4-89e4-6ab926ce62e2.png)
This still does not solve the problem with small values. I think general practice for these situations is to plot charts on a log scale.

Call out will interfere with other bars, so I dont think that is a good idea.

**Comment by Autio** [comment]
@grassick any thoughts on stacked charts where there are values so small that the labels won't render nicely? Put them on a log scale instead?

**Comment by grassick** [comment]
Log scale is only really for things that are intrinsically exponential like pandemics, etc. 

Maybe minimum size? But we'd need to do surgery on C3 which is scary. We also should update to a newer version of C3 (now called Billboard. I don't see a good easy solution to this one.

**Comment by Autio** [comment]
Ok, can we then just start with an update from C3 to Billboard? The migration process seems straightforward. 

They also look to have sparklines on the near-term roadmap which @rocketboy76 may appreciate.

**Comment by Autio** [comment]
Here's an example provided by WaterAid of a style they like https://washdata.org/monitoring/drinking-water

![image](https://user-images.githubusercontent.com/5147940/161505012-c1eb80ef-afcd-4ccb-8132-c699adc7e3e3.png)

Simple black and white colours for the stacked bar chart values depending on the colour, with some pop-outs. The axis labels are pretty clear too. The combination of two series in sort of the same bar seems more tricky to pull off though.

**Comment by broncha** [comment]
@grassick I imported the changes in the billboard branch into fresh branch from master. The integration works fine. I fixed some issues caused by billboard.
But the tests are failing. For some reasons, the exported modules while building for browser are not available while testing with mocha.
Can you take a look? the new branch is `bboard`

**Comment by grassick** [comment]
@broncha There was something weird about the imports of types. I've added a temporary hack to make the tests work, but was unable to resolve the problem of importing types in general within a node (mocha) environment.

**Comment by broncha** [comment]
@grassick  @Autio progress here. Does this look readable or understandable?
Adjusting the labels' color contrast will also not work, as the texts bleed outside the bar and the part that bleeds would not be visible!
<img width="709" alt="Screen Shot 2022-04-25 at 17 09 59" src="https://user-images.githubusercontent.com/46905/165079991-c9d20103-c97f-4211-8697-7a9b1ef18e68.png">

**Comment by Autio** [comment]
That's certainly clearly legible to me. What about the contrast only for cases where there's no extension and the text won't bleed outside? But I suppose in some cases the number just is too wide for the bar anyway. 

Feels like maybe we could have a toggle to not show popout labels like that to give users a choice. I do wish the month labels could show more elegantly somehow.

**Comment by broncha** [comment]
@Autio This is just way too much data! I dont think we will be able to come up with something to properly visualize this!
<img width="500" alt="Screen Shot 2022-04-28 at 18 56 24" src="https://user-images.githubusercontent.com/46905/165760015-6c88052f-4e8e-469d-acf0-43244fb589ab.png">
<img width="1482" alt="Screen Shot 2022-04-28 at 18 56 31" src="https://user-images.githubusercontent.com/46905/165760029-1144dde5-13e8-458d-803a-e4a843d8fa4c.png">

**Comment by grassick** [comment]
Yep, that's crazy! They'd be better to use a pivot table.
