### ISSUE TITLE
Billboard feedback

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#464]
Brian did some thorough testing of the billboard updates in portalbeta. 

- [ ] Pie and doughnut charts don’t have black percentages by default
![image](https://user-images.githubusercontent.com/5147940/165259008-f1791342-87d8-4347-b235-f5b0f3080e9f.png)

- [ ] Bar chart Y-Threshold is too light and solid. It should be a black and dotted line.
![image](https://user-images.githubusercontent.com/5147940/165260050-8f18bebb-a274-4ec6-89aa-0daaf993716e.png)

- [ ] Linear trend line looks unattractive. Make it dotted, no markers, and display numbers on the line.
![image](https://user-images.githubusercontent.com/5147940/165260184-d9e9c73b-b0a9-4e28-a545-c77e9cd3546c.png)

- [ ] The Categories’ formats wrap too early. 
![image](https://user-images.githubusercontent.com/5147940/165260439-7fbb6a98-c8f5-4c09-a1ab-f675269b86dd.png)

**Comment by broncha** [comment]
@Autio do you have the URLs for these visualizations?

**Comment by Autio** [comment]
I found a dashboard Brian would have used for testing. Here's a duplicate https://share.mwater.co/v3/dashboard_link/609dcf6eccbc41ebb7a410d71c5457a6?share=e5c7ebc47fb14300b94642c82cf61ed1

**Comment by broncha** [comment]
@Autio I dont see any of the issues mentioned above in portal beta!

https://portalbeta.mwater.co/#/dashboards/609dcf6eccbc41ebb7a410d71c5457a6?share=e5c7ebc47fb14300b94642c82cf61ed1

**Comment by Autio** [comment]
Are the Billboard updates still currently deployed there or have they been overwritten? I can talk to Brian later today about this.

**Comment by broncha** [comment]
beta has the latest billboard updates
