### ISSUE TITLE
Option for bar charts to only show entries with data

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#466]
A suggestion from Tim Davis:

Can there be an option in bar charts where you toggle the option to hide entries in a bar chart where no data is coming through? Similar to what we've relatively recently implemented in pivot tables (Only show values actually present). 

![image](https://user-images.githubusercontent.com/5147940/169037465-789f470e-06c6-410b-a0c0-35ba0b9dbcc5.png)

The use case is his MIS where he has a stacked bar chart for all of the districts in PNG but only a handful have data at the moment, so he's manually unticking most of them. But data will gradually come for more and more of them, so it would be best not to have to manually manage this. 

Hoping this is somehow easier to implement now that the equivalent thing has been done for pivot tables.

Example:
![image](https://user-images.githubusercontent.com/5147940/169038219-c059575d-3bf5-48f2-b956-bb3aa32df6dc.png)
https://portal.mwater.co/#/consoles/23e566cb28cb46458745fcda0b4bd9a4?tab=e56ffccc-9bb5-42e0-bfad-819ceb29f97e

**Comment by broncha** [comment]
Deployed
<img width="383" alt="Screen Shot 2022-07-05 at 16 42 54" src="https://user-images.githubusercontent.com/46905/177313025-1659f14d-5989-4d40-b838-639d16d028b4.png">
