### ISSUE TITLE
Sticky color choices

### ISSUE THREAD

**Issue by Autio** [mWater/mwater-visualization#470]
When I'm choosing a color scheme, it defaults to the basic scheme too easily. 

For example, when I change the number of bins, or toggle the Include < 0 and Include > x options, it always reverts to the basic scheme. This is particularly unpleasant when the colors have been individually set and are lost. 

Could the chosen colors be sticky so they don't revert during such changes? 
![image](https://user-images.githubusercontent.com/5147940/195592332-f18057aa-cbfb-48b1-97d8-39342fdcf7d5.png)

**Comment by broncha** [comment]
We only change color when the bins/categories no longer match, which is happening in this case.
When you change the range, the bins no longer match, and we reset the colors.
There is a code block specifically handling this. Do we really want this?

**Comment by Autio** [comment]
It's just an annoyance and not critical, we can leave it.
